version: '3.7'

services:

 rabbitmq:
  image: rabbitmq:management
  ports:
  - "5672:5672"
  - "15672:15672"
  tty:
    true

 weatherbackend:
   build: ./weatherbackend
   ports:
   - "8090"
   tty:
     true
   restart:
     unless-stopped
